name: mooshaf_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  build_runner: ^2.4.4
  floor: ^1.4.2
  floor_generator: ^1.4.2
  flutter:
    sdk: flutter
  flutter_statusbarcolor_ns: ^0.5.0
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15
  percent_indicator: ^4.2.3
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sql/database_quransuhuf.db
  
